name: first_actions
on: 
  push: 
    branch:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello world from job-1"
      - name: sleep
        run: sleep 3
  job-2: 
    needs: [job-1]
    runs-on: ubuntu-latest
    steps: 
      - name: print goodbye
        run: echo "goodbye from job-2"
      - name: sleep
        run: sleep 3
  job-3:
    needs: [job-2]
    runs-on: ubuntu-latest
    steps: 
      - name: multiline command
        run: |
          touch 1.txt
          ls -la
    
