name: first_actions
on: 
  push: 
    branch:
      - main
jobs:
  job-1:
    run-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello world from job-1"
      - name: sleep
        run: sleep 3
  job-2: 
    runs-on: ubuntu-latest
    steps: 
      - name: print goodbye
        run: echo "goodbye from job-2"
      - name: sleep
        run: sleep 3
    
