name: first_actions
env: 
  APP_NAME: "MyApp"
  PACKAGE_NAME: "MyApp-version-${{ github.sha }}"
on: 
  push: 
    branch:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello world from job-1"
      - name: sleep
        run: sleep 3
  job-2: 
    needs: [job-1]
    runs-on: ubuntu-latest
    steps: 
      - name: print goodbye
        run: echo "goodbye from job-2"
      - name: sleep
        run: sleep 3
  job-3:
    needs: [job-2]
    runs-on: ubuntu-latest
    steps: 
      - name: multiline command
        run: |
          touch 1.txt
          ls -la
          pwd
      - uses: actions/checkout@v2
      - run: ls -la
  job-4:
    needs: [job-3]
    runs-on: ubuntu-latest
    env: 
      VAR1: "This is a job level Variable"
    steps: 
      - name: print env
        run: |
          echo "My app name is :${{ env.APP_NAME }}"
          echo "App package :${{ env.PACKAGE_NAME }}" 
          echo "Var1 - ${{ env.VAR1 }}"
          echo "local Variable: $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is a local Variable"
